### ISSUE TITLE
yolov4.weights convert to .onnx failed

### ISSUE THREAD

**Issue by j22054022** [james77777778/darknet-onnx#3]
after I executed: 
`$ python3 main.py --cfg /home/jason/test_yolov4_onnx/yolov4.cfg --weight /home/jason/test_yolov4_onnx/yolov4.weights --img /home/jason/yolov5_web/webserver/img_2.jpg --names /home/jason/test_yolov4_onnx/coco.names`

get error message:
cfg       : /home/jason/test_yolov4_onnx/yolov4.cfg
weight    : /home/jason/test_yolov4_onnx/yolov4.weights
img       : /home/jason/yolov5_web/webserver/img_2.jpg
batch_size: 1
to_float16: False
out       : model.onnx
score     : 0.3
nms       : 0.45
names     : /home/jason/test_yolov4_onnx/coco.names
no_export : False
Traceback (most recent call last):
  File "main.py", line 120, in <module>
    main(args)
  File "main.py", line 94, in main
    export_to_onnx(args.cfg, args.weight, args.out, args.batch_size, args.to_float16)
  File "/home/jason/darknet-onnx/darknetonnx/darknet.py", line 41, in export_to_onnx
    torch.onnx._export(
  File "/home/jason/.local/lib/python3.8/site-packages/torch/onnx/__init__.py", line 30, in _export
    result = utils._export(*args, **kwargs)
TypeError: _export() got an unexpected keyword argument 'example_outputs'

this yolov4.weights is downloaded from https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.weights

可以幫我看一下是甚麼原因嗎?謝謝!

**Comment by james77777778** [comment]
Hi @j22054022 

I can successfully convert the model with weights from
[https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.weights](https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.weights)

```bash
cfg       : cfg/yolov4.cfg
weight    : weights/yolov4.weights
img       : data/dog.jpg
batch_size: 1
to_float16: False
out       : model.onnx
score     : 0.3
nms       : 0.45
names     : data/coco.names
no_export : False

...

Preprocessing : 0.0289s
Inference     : 0.7271s
Postprocessing: 0.0114s
Total         : 0.7674s
bicycle: 99%    (left_x:  128   top_y:  130     width:  440     height:  294)
dog: 99%        (left_x:  132   top_y:  233     width:  178     height:  303)
truck: 91%      (left_x:  465   top_y:  75      width:  227     height:  96)
save visulization to onnx_predictions.jpg
```

I think the problem comes from `torch`. Please verify your `torch` version and it should be `>= 1.9.1`

```bash
pip3 list | grep torch

>> torch                1.9.1+cpu
```

**Comment by james77777778** [comment]
Hi @j22054022 

Has the above comment solved your issue?
[comment](https://github.com/james77777778/darknet-onnx/issues/3#issuecomment-1169896793)

Feel free to reopen the issue if it is not solved yet.

**Comment by j22054022** [comment]
hi, sorry for not noticed your reply in time,
after executing
`$ pip3 list | grep torch`
I got
`torch                   1.11.0`
`torchvision             0.12.0`
and it still getting the same error.

**Comment by james77777778** [comment]
> hi, sorry for not noticed your reply in time, after executing `$ pip3 list | grep torch` I got `torch 1.11.0` `torchvision 0.12.0` and it still getting the same error.

Hi @j22054022 

I fixed the keyword argumenrt issue due to `torch > 1.10.1`. The newest version of this repo should be fine now.

Thx for the information about the issue.

You could check [darknet-onnx#typeerror-export-got-an-unexpected-keyword-argument-example_outputs](https://github.com/james77777778/darknet-onnx#typeerror-export-got-an-unexpected-keyword-argument-example_outputs) for the detail.
